[package]
name = "quadtree"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"

[dev-dependencies]
kdtree = "0.7.0"
criterion = "0.5.1"

[[bench]]
name = "benches"
harness = false

[profile.bench]
debug = 1
